### ISSUE TITLE
Refactor repositories (git & maven)

### ISSUE THREAD

**Issue by mdutoo** [easysoa/EasySOA#29]
According to new tree and naming plan, and first all proxy related repos to easysoa-proxy (while making sure it will play well when merging with easysoa-model-demo in a second time).

Use git-branch-filter to refactor trees, git merge to merge repos while still keeping history.

**Comment by JGuillemotte** [comment]
- OK, proxy repo is now at https://github.com/easysoa/EasySOA , see repo merge method at https://github.com/easysoa/easysoa-model-demo/wiki/Git-Quickstart
- OK rename /easysoa/ to easysoa-proxy and /easysoa/easysoa-proxy to /easysoa-proxy/easysoa-proxy-core
- OK remove useless (non root) .gitignore, remove obsolete maven conf (galaxy parent & distribution)
- OK add common version number as variables for junit, log4j, frascati components in the main pom.xml
- OK FraSCAti MUST be in version 1.5-SNAPSHOT, at least for scaffoldingProxy project because the fraSCAti Velocity implementation only exists in this version !! To avoid lengthy builds because of SNAPSHOT downloads, use maven offline thanks to its -o option
- OK add easysoa-parent/pom.xml (at least) in the first level directories below the root with all maven repo defs, and also in tests bigger than one project in order to share build conf (ex. smarttravel-parent), make all other unparented poms inherit from them (so they will have the maven repo defs)
- OK remove useless App(Test).java code (do a find / grep or CTRL-MAJ-T App in Eclipse to find them)
- OK add a maven profile that only runs tests that require external remote applications (like Nuxeo, FraSCAti apps) to be started, and by default don't run them, by requring a test naming pattern (ex. *RemoteTest) and configuring the maven surefire plugin with [includes & excludes](http://maven.apache.org/plugins/maven-surefire-plugin/examples/inclusion-exclusion.html). Related : [#35 continuous integration](https://github.com/easysoa/easysoa-model-demo/issues/35)
- OK launch easysoa-sonar with testing enabled and if ok schedule it every night
- OK study unified proxy architecture (see #30)

Still TODO :
- put these (which profiles & which tests to put in them) as guidelines in the dev wiki
